version: "3.8"
services:
  e2e:
    image: cypress/included:8.5.0
    working_dir: /app
    volumes:
      - '.:/app'
    entrypoint: npx start-server-and-test serve:ci http://localhost:8081/next/ cypress:run
