service_list:
  - name: web.brick_next
    port: 80
    host: ~
start_script: ""
stop_script: ""
restart_script: ""
install_prescript: ""
install_postscript: ""
update_prescript: ""
update_postscript: ""
rollback_prescript: ""
rollback_postscript: ""
proc_guard: stopStart
port_guard: stopStart
user: easyops:easyops
dependencies:
  - name: api_gateway
    version: ^1.18.2
  - name: nginx
    version: ^3.5.5
  - name: ucpro_desktop_service
    version: ^1.17.18
  - name: api_service
    version: ^1.0.6
  - name: api_service-R
    version: ^1.0.4
  - name: cmdb_service
    version: ~2.31.1 || ^2.32.1
  - name: micro_app_service
    version: ^1.16.4
  - name: object_store_service
    version: ^1.0.12
start_dependencies:
  - name: logic.api.gateway   # 依赖服务名
